name: "Gitbook Action"

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"  # To avoid loop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Gitbook Action
      uses: meese-enterprises/gitbook-action@master
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        source_branch: master
        source_dir: docs-src
        source_edit_time: true
        publish_commit_message: ${{ github.event.head_commit.message }}
        publish_branch: master
        publish_dir: docs
